title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

minima:
  skin: solarized-dark
  
  social_links:
    twitter: alprog_
    github:  alprog
    telegram: alprog

theme: minima
